  
on:
  push:

jobs:
  logging-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: log some metadata
        run: |
          echo "::debug::[barcelona]{my_metadata_key:my_metadata_value}"
      - name: capture metadata
        uses: ./ # Uses an action in the root directory
